version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "teleport-cli-form"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hgnohp0ks60o"
s3_prefix = "teleport-cli-form"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ValidatedEmail=\"ben@goteleport.com\""
